### PR TITLE
Pass a destination buffer for HID comms

### PR DESCRIPTION
**Pull request by yhql**
## Description

This PR removes the forced usage of `G_io_apdu_buffer` for HID communication and allows passing manually a different destination buffer.
This behaviour is only active if `HAVE_LOCAL_APDU_BUFFER` is defined, which is only the case for the [Rust SDK](https://github.com/LedgerHQ/ledger-nanos-sdk/) at the moment. Merging this PR would allow this Rust SDK to have `ledger-secure-sdk` as a submodule instead of manually upgrading the necessary files when upgrading OS versions.

## Changes include

- [x] New feature (non-breaking change that adds functionality)

### CODE REVIEW

**Comment by cbouvet-ledger** [comment]
@yhql j'imagine que tu as testé sur des apps non rust? :innocent:

**Comment by yhql** [comment]
@cbouvet-ledger oui, avec l'app btc.

**Comment by xchapron-ledger** [comment]
@yhql this is breaking the build of two apps, is it expected?
https://github.com/LedgerHQ/ledger-secure-sdk/actions/runs/4617218814/jobs/8163224070?pr=188
https://github.com/LedgerHQ/ledger-secure-sdk/actions/runs/4617218814/jobs/8163225995?pr=188

**Comment by yhql** [comment]
> @yhql this is breaking the build of two apps, is it expected? https://github.com/LedgerHQ/ledger-secure-sdk/actions/runs/4617218814/jobs/8163224070?pr=188 https://github.com/LedgerHQ/ledger-secure-sdk/actions/runs/4617218814/jobs/8163225995?pr=188

No, I 'll update the corresponding ccid prototype

**Pull request merged**
